In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from allensdk.brain_observatory.ecephys.ecephys_project_cache import (
    EcephysProjectCache,
)

In [3]:
manifest_path = "data/allen_cache/manifest.json"

cache = EcephysProjectCache.from_warehouse(manifest=manifest_path)

In [4]:
selected_session_ids = [
    732592105,
    797828357,
    755434585,
    756029989,
    791319847,
]

In [5]:
session_id = selected_session_ids[0]

session = cache.get_session_data(session_id)

print("Loaded session:", session_id)
print(type(session))

/opt/anaconda3/envs/allen-vc/lib/python3.11/site-packages/hdmf/spec/namespace.py:535: UserWarning: Ignoring cached namespace 'hdmf-common' version 1.1.3 because version 1.8.0 is already loaded.
  warn("Ignoring cached namespace '%s' version %s because version %s is already loaded."
/opt/anaconda3/envs/allen-vc/lib/python3.11/site-packages/hdmf/spec/namespace.py:535: UserWarning: Ignoring cached namespace 'core' version 2.2.2 because version 2.7.0 is already loaded.
  warn("Ignoring cached namespace '%s' version %s because version %s is already loaded."


Loaded session: 732592105
<class 'allensdk.brain_observatory.ecephys.ecephys_session.EcephysSession'>


In [6]:
units = session.units.copy()

print(units.shape)
print(units.columns.tolist())

display(
    units[
        [
            "ecephys_structure_acronym",
            "firing_rate",
            "presence_ratio",
            "amplitude_cutoff",
            "isi_violations",
        ]
    ].describe(include="all")
)
# filter bad neurons
target_areas = ["VISp", "VISl", "VISpm"]

good_units = units[
    units["ecephys_structure_acronym"].isin(target_areas)
    & (units["presence_ratio"] > 0.9)
    & (units["amplitude_cutoff"] < 0.1)
    & (units["isi_violations"] < 0.5)
].copy()

print("Units before filtering:")
print(
    units[
        units["ecephys_structure_acronym"].isin(target_areas)
    ]["ecephys_structure_acronym"].value_counts()
)

print("\nUnits after filtering:")
print(
    good_units[
        "ecephys_structure_acronym"
    ].value_counts()
)

/opt/anaconda3/envs/allen-vc/lib/python3.11/site-packages/hdmf/spec/namespace.py:535: UserWarning: Ignoring cached namespace 'hdmf-common' version 1.1.3 because version 1.8.0 is already loaded.
  warn("Ignoring cached namespace '%s' version %s because version %s is already loaded."
/opt/anaconda3/envs/allen-vc/lib/python3.11/site-packages/hdmf/spec/namespace.py:535: UserWarning: Ignoring cached namespace 'core' version 2.2.2 because version 2.7.0 is already loaded.
  warn("Ignoring cached namespace '%s' version %s because version %s is already loaded."
/opt/anaconda3/envs/allen-vc/lib/python3.11/site-packages/hdmf/spec/namespace.py:535: UserWarning: Ignoring cached namespace 'hdmf-common' version 1.1.3 because version 1.8.0 is already loaded.
  warn("Ignoring cached namespace '%s' version %s because version %s is already loaded."
/opt/anaconda3/envs/allen-vc/lib/python3.11/site-packages/hdmf/spec/namespace.py:535: UserWarning: Ignoring cached namespace 'core' version 2.2.2 because vers

(824, 40)
['waveform_PT_ratio', 'waveform_amplitude', 'amplitude_cutoff', 'cluster_id', 'cumulative_drift', 'd_prime', 'firing_rate', 'isi_violations', 'isolation_distance', 'L_ratio', 'local_index', 'max_drift', 'nn_hit_rate', 'nn_miss_rate', 'peak_channel_id', 'presence_ratio', 'waveform_recovery_slope', 'waveform_repolarization_slope', 'silhouette_score', 'snr', 'waveform_spread', 'waveform_velocity_above', 'waveform_velocity_below', 'waveform_duration', 'filtering', 'probe_channel_number', 'probe_horizontal_position', 'probe_id', 'probe_vertical_position', 'structure_acronym', 'ecephys_structure_id', 'ecephys_structure_acronym', 'anterior_posterior_ccf_coordinate', 'dorsal_ventral_ccf_coordinate', 'left_right_ccf_coordinate', 'probe_description', 'location', 'probe_sampling_rate', 'probe_lfp_sampling_rate', 'probe_has_lfp_data']


,ecephys_structure_acronym,firing_rate,presence_ratio,amplitude_cutoff,isi_violations
count,824,824.000000,824.000000,824.000000,824.000000
unique,6,NaN,NaN,NaN,NaN
top,grey,NaN,NaN,NaN,NaN
freq,459,NaN,NaN,NaN,NaN
mean,NaN,7.835941,0.988422,0.018169,0.091670
std,NaN,8.914525,0.006152,0.024926,0.115301
min,NaN,0.058849,0.950000,0.000001,0.000000
25%,NaN,1.984085,0.990000,0.000882,0.009768
50%,NaN,5.064790,0.990000,0.005445,0.044240
75%,NaN,10.904755,0.990000,0.027991,0.124298


Units before filtering:
VISp     110
VISpm     66
VISl      40
Name: ecephys_structure_acronym, dtype: int64

Units after filtering:
VISp     110
VISpm     66
VISl      40
Name: ecephys_structure_acronym, dtype: int64


In [57]:
print(
    static_trials["orientation"]
    .value_counts(dropna=False)
)
binary_trials = static_trials[
    static_trials["orientation"].isin([0.0, 90.0])
].copy()

print(
    binary_trials["orientation"]
    .value_counts()
)

0.0      981
30.0     972
90.0     967
60.0     966
150.0    965
120.0    956
null     193
Name: orientation, dtype: int64
0.0     981
90.0    967
Name: orientation, dtype: int64


In [58]:
print(
    binary_trials["spatial_frequency"]
    .value_counts(dropna=False)
)
simple_trials = binary_trials[
    binary_trials["spatial_frequency"] == 0.02
].copy()

print(
    simple_trials["orientation"]
    .value_counts()
)

0.02    394
0.08    391
0.32    389
0.16    387
0.04    387
Name: spatial_frequency, dtype: int64
0.0     200
90.0    194
Name: orientation, dtype: int64


In [61]:
#print(simple_trials["phase shift"].value_counts(dropna=False))

In [63]:
y = (
    simple_trials["orientation"] == 90.0
).astype(int).to_numpy()

print(
    pd.Series(y).value_counts().sort_index()
)

0    200
1    194
dtype: int64


In [64]:
unit_ids = good_units.index.to_numpy()

print("Number of neurons:", len(unit_ids))

Number of neurons: 195
[951087521 951087534 951087567 951087547 951087588 951087601 951087631
 951087637 951087693 951087687]


In [67]:
spike_times = session.spike_times

print(type(spike_times))
print("Number of units with spike times:", len(spike_times))

<class 'dict'>
Number of units with spike times: 611


In [68]:
missing_unit_ids = [
    unit_id
    for unit_id in unit_ids
    if unit_id not in spike_times
]

print("Missing selected neurons:", len(missing_unit_ids))

Missing selected neurons: 0


In [69]:
trial_onsets = simple_trials["start_time"].to_numpy()

print("Number of trial onsets:", len(trial_onsets))
print("First 5 onset times:", trial_onsets[:5])

print(
    simple_trials["duration"]
    .describe()
)

Number of trial onsets: 394
First 5 onset times: [5394.51776461 5398.77129992 5399.02150774 5406.27754429 5408.02901961]
count    394.000000
mean       0.250209
std        0.000006
min        0.250195
25%        0.250205
50%        0.250210
75%        0.250213
max        0.250225
Name: duration, dtype: float64


In [70]:
window_start = 0.0
window_end = 0.25

print("Response window:", window_start, "to", window_end, "seconds")

Response window: 0.0 to 0.25 seconds


In [71]:
X = np.zeros(
    (len(simple_trials), len(unit_ids)),
    dtype=np.float32,
)

print("X shape:", X.shape)
print("Number of unit IDs:", len(unit_ids))
print("Number of rows in good_units:", len(good_units))
print("Number of columns in X:", X.shape[1])

X shape: (394, 195)
Number of unit IDs: 195
Number of rows in good_units: 195
Number of columns in X: 195


In [72]:
for neuron_index, unit_id in enumerate(unit_ids):
    spikes = np.asarray(spike_times[unit_id])

    start_indices = np.searchsorted(
        spikes,
        trial_onsets + window_start,
        side="left",
    )

    end_indices = np.searchsorted(
        spikes,
        trial_onsets + window_end,
        side="left",
    )

    X[:, neuron_index] = (
        end_indices - start_indices
    )

In [73]:
print("X shape:", X.shape)
print("X dtype:", X.dtype)
print("Minimum spike count:", X.min())
print("Maximum spike count:", X.max())
print("Mean spike count:", X.mean())
print("Fraction of zero entries:", np.mean(X == 0))

X shape: (394, 195)
X dtype: float32
Minimum spike count: 0.0
Maximum spike count: 40.0
Mean spike count: 1.5337108
Fraction of zero entries: 0.46785109983079526


In [74]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    stratify=y,
    random_state=42,
)

print("Training shape:", X_train.shape)
print("Test shape:", X_test.shape)
print("Training labels:", np.bincount(y_train))
print("Test labels:", np.bincount(y_test))

Training shape: (315, 195)
Test shape: (79, 195)
Training labels: [160 155]
Test labels: [40 39]


In [75]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("Scaled training shape:", X_train_scaled.shape)
print("Scaled test shape:", X_test_scaled.shape)

Scaled training shape: (315, 195)
Scaled test shape: (79, 195)


In [76]:
from sklearn.model_selection import StratifiedKFold, cross_val_score
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

cv_model = Pipeline([
    ("scaler", StandardScaler()),
    (
        "classifier",
        LogisticRegression(
            max_iter=2000,
            random_state=42,
        ),
    ),
])

cv = StratifiedKFold(
    n_splits=10,
    shuffle=True,
    random_state=42,
)

cv_scores = cross_val_score(
    cv_model,
    X,
    y,
    cv=cv,
    scoring="accuracy",
)

print("Fold accuracies:", cv_scores)
print("Mean accuracy:", cv_scores.mean())
print("Standard deviation:", cv_scores.std())

Fold accuracies: [0.425      0.35       0.475      0.475      0.41025641 0.48717949
 0.48717949 0.43589744 0.48717949 0.43589744]
Mean accuracy: 0.4468589743589743
Standard deviation: 0.042309100598161835


In [77]:
area_scores = {}

for area in ["VISp", "VISl", "VISpm"]:
    area_mask = unit_areas == area
    X_area = X[:, area_mask]

    scores = cross_val_score(
        cv_model,
        X_area,
        y,
        cv=cv,
        scoring="accuracy",
    )

    area_scores[area] = scores

    print(
        area,
        "neurons:", X_area.shape[1],
        "mean accuracy:", scores.mean(),
        "std:", scores.std(),
    )

IndexError: boolean index did not match indexed array along dimension 1; dimension is 195 but corresponding boolean dimension is 216

In [ ]:
n_neurons_equal = 40
n_repeats = 20

rng = np.random.default_rng(42)

print("Neurons per area:", n_neurons_equal)
print("Number of repeated samples:", n_repeats)

equal_size_results = {
    "VISp": [],
    "VISl": [],
    "VISpm": [],
}

for area in ["VISp", "VISl", "VISpm"]:
    area_indices = np.where(unit_areas == area)[0]

    for _ in range(n_repeats):
        sampled_indices = rng.choice(
            area_indices,
            size=n_neurons_equal,
            replace=False,
        )

        X_sampled = X[:, sampled_indices]

        scores = cross_val_score(
            cv_model,
            X_sampled,
            y,
            cv=cv,
            scoring="accuracy",
        )

        equal_size_results[area].append(
            scores.mean()
        )

for area in ["VISp", "VISl", "VISpm"]:
    values = np.array(equal_size_results[area])

    print(
        area,
        "mean accuracy:", values.mean(),
        "std across samples:", values.std(),
        "min:", values.min(),
        "max:", values.max(),
    )

Neurons per area: 40
Number of repeated samples: 20
VISp mean accuracy: 0.8287980769230769 std across samples: 0.029814390445384767 min: 0.7462179487179487 max: 0.8833333333333334
VISl mean accuracy: 0.9059615384615387 std across samples: 1.1102230246251565e-16 min: 0.9059615384615386 max: 0.9059615384615386
VISpm mean accuracy: 0.9145865384615386 std across samples: 0.036380424505890505 min: 0.8475641025641025 max: 0.9517307692307693


Test 6 orientation: 0, 30, 60, 90, 120, 150

In [ ]:
six_orientation_trials = static_trials[
    (static_trials["spatial_frequency"] == 0.02)
    & (static_trials["orientation"] != "null")
].copy()

print(
    six_orientation_trials["orientation"]
    .value_counts()
    .sort_index()
)

0.0      200
30.0     197
60.0     193
90.0     194
120.0    190
150.0    192
Name: orientation, dtype: int64


In [ ]:
six_y = six_orientation_trials["orientation"].astype(float).to_numpy()
six_trial_onsets = six_orientation_trials["start_time"].to_numpy()

print("Number of trials:", len(six_y))
print("Labels:", np.unique(six_y))

Number of trials: 1166
Labels: [  0.  30.  60.  90. 120. 150.]


In [ ]:
six_X = np.zeros(
    (len(six_orientation_trials), len(unit_ids)),
    dtype=np.float32,
)

for neuron_index, unit_id in enumerate(unit_ids):
    spikes = np.asarray(spike_times[unit_id])

    start_indices = np.searchsorted(
        spikes,
        six_trial_onsets + window_start,
        side="left",
    )

    end_indices = np.searchsorted(
        spikes,
        six_trial_onsets + window_end,
        side="left",
    )

    six_X[:, neuron_index] = end_indices - start_indices

print("Feature matrix shape:", six_X.shape)
print("Mean spike count:", six_X.mean())
print("Maximum spike count:", six_X.max())

Feature matrix shape: (1166, 216)
Mean spike count: 1.6099994
Maximum spike count: 39.0


In [ ]:
six_cv_scores = cross_val_score(
    cv_model,
    six_X,
    six_y,
    cv=cv,
    scoring="accuracy",
)

print("Fold accuracies:", six_cv_scores)
print("Mean accuracy:", six_cv_scores.mean())
print("Standard deviation:", six_cv_scores.std())
print("Chance level:", 1 / 6)

Fold accuracies: [0.68376068 0.67521368 0.7008547  0.67521368 0.58119658 0.7008547
 0.63793103 0.67241379 0.65517241 0.68103448]
Mean accuracy: 0.6663645741231947
Standard deviation: 0.03358197792384858
Chance level: 0.16666666666666666


In [ ]:
six_area_scores = {}

for area in ["VISp", "VISl", "VISpm"]:
    area_mask = unit_areas == area
    six_X_area = six_X[:, area_mask]

    scores = cross_val_score(
        cv_model,
        six_X_area,
        six_y,
        cv=cv,
        scoring="accuracy",
    )

    six_area_scores[area] = scores

    print(
        area,
        "neurons:", six_X_area.shape[1],
        "mean accuracy:", scores.mean(),
        "std:", scores.std(),
    )

VISp neurons: 110 mean accuracy: 0.6063586796345416 std: 0.04319019448780838
VISl neurons: 40 mean accuracy: 0.5385352195697023 std: 0.03907661438282501
VISpm neurons: 66 mean accuracy: 0.6303787208959623 std: 0.04681400107398062


In [ ]:
six_equal_results = {
    "VISp": [],
    "VISl": [],
    "VISpm": [],
}

rng = np.random.default_rng(42)

for area in ["VISp", "VISl", "VISpm"]:
    area_indices = np.where(unit_areas == area)[0]

    for _ in range(n_repeats):
        sampled_indices = rng.choice(
            area_indices,
            size=40,
            replace=False,
        )

        scores = cross_val_score(
            cv_model,
            six_X[:, sampled_indices],
            six_y,
            cv=cv,
            scoring="accuracy",
        )

        six_equal_results[area].append(scores.mean())

for area in ["VISp", "VISl", "VISpm"]:
    values = np.array(six_equal_results[area])

    print(
        area,
        "mean accuracy:", values.mean(),
        "std across samples:", values.std(),
    )

VISp mean accuracy: 0.4909762746831712 std across samples: 0.02999722384586051
VISl mean accuracy: 0.5385352195697023 std across samples: 0.0
VISpm mean accuracy: 0.5652402004126141 std across samples: 0.0320903806192493


In [ ]:
from sklearn.model_selection import cross_val_predict
from sklearn.metrics import confusion_matrix

six_y_pred = cross_val_predict(
    cv_model,
    six_X,
    six_y,
    cv=cv,
)

six_cm = confusion_matrix(
    six_y,
    six_y_pred,
    labels=[0, 30, 60, 90, 120, 150],
)

print(six_cm)

[[136  39   4   1   4  16]
 [ 33 130  19   8   3   4]
 [  1  25 123  31   8   5]
 [  2   1  31 127  29   4]
 [  8   2  10  25 126  19]
 [ 24   5   7   4  17 135]]
